export const requirements = [
    {
      id: "requirement1",
      projectId: "project1",
      title: "Requirement 1",
      description: "Lorem ipsum dolor sit amet",
      status: "pending",
    },
    {
      id: "requirement2",
      projectId: "project2",
      title: "Requirement 2",
      description: "Consectetur adipiscing elit",
      status: "completed",
    },
    {
      id: "requirement3",
      projectId: "project1",
      title: "Requirement 3",
      description: "Sed do eiusmod tempor incididunt",
      status: "pending",
    },
    {
      id: "requirement4",
      projectId: "project3",
      title: "Requirement 4",
      description: "Ut enim ad minim veniam",
      status: "completed",
    },
    {
      id: "requirement5",
      projectId: "project1",
      title: "Requirement 5",
      description: "Duis aute irure dolor in reprehenderit",
      status: "pending",
    },
    {
      id: "requirement6",
      projectId: "project2",
      title: "Requirement 6",
      description: "Excepteur sint occaecat cupidatat non proident",
      status: "completed",
    },
    {
      id: "requirement7",
      projectId: "project3",
      title: "Requirement 7",
      description: "Sunt in culpa qui officia deserunt mollit",
      status: "pending",
    },
    {
      id: "requirement8",
      projectId: "project1",
      title: "Requirement 8",
      description: "Lorem ipsum dolor sit amet",
      status: "pending",
    },
    {
      id: "requirement9",
      projectId: "project2",
      title: "Requirement 9",
      description: "Consectetur adipiscing elit",
      status: "completed",
    },
    {
      id: "requirement10",
      projectId: "project3",
      title: "Requirement 10",
      description: "Sed do eiusmod tempor incididunt",
      status: "pending",
    },
  ];